![NumPy Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png)

# Основы Numpy *(Numerical Python)* 
# Часть 3

## [Документация](https://docs.scipy.org/doc/numpy/reference/)

In [1]:
import numpy as np

---

## Выполнение вычислений над массивами 

Из-за особенностей строения Python выполнение операций с каждым элементом массивом не особо эфективно по времени, поэтому лучше использовать **векторизованные операции**, например если мы хотим каждый элемент взять со знаком минус:

In [2]:
np.array([1,2,3,4])*-1

array([-1, -2, -3, -4])

In [3]:
%timeit 1.0 / np.arange(1, 1000000)

10.1 ms ± 4.17 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


---

In [4]:
def func(a):
    b = np.empty(len(a))
    for i in range(len(a)):
        b[i] = 1.0 / a[i]
    return b

In [5]:
%timeit func(np.arange(1, 1000000))

3.04 s ± 120 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


> Целых 2.5 секунды(!) для обработки всего 1000000 элементов, по сравнению с 6 милисекндами при использовании **векторизированных операций**

---

Так же можно поступать и с 2 массивами numpy

In [6]:
np.array([[1,2],[3,4]]) * np.array([[5,6],[7,8]])

array([[ 5, 12],
       [21, 32]])

---

## Универсальные операции

### Арифметические и тригонометрические операции

>* \+ np.add()
* \- np.subtract()
* \- np.negative()
* \*  np.multiply()
* \** np.power()
* /  np.divide()
* //  np.floor_divide()
* %  np.mod()
* abs()
* np.sin(), np.arcsin()
* np.cos(), np.arccos()
* np.tan(), np.arctan()
* np.exp() - *e^*
* np.ln(), np.log2(), np.log10()

In [54]:
a = np.array([1,2,3,4,5], dtype="int64")

In [55]:
-a

array([-1, -2, -3, -4, -5])

In [56]:
a + 2

array([3, 4, 5, 6, 7])

In [57]:
a ** 10

array([      1,    1024,   59049, 1048576, 9765625])

In [58]:
a + a

array([ 2,  4,  6,  8, 10])

In [59]:
a % 2

array([1, 0, 1, 0, 1])

In [60]:
abs(a)

array([1, 2, 3, 4, 5])

In [61]:
np.sin(np.linspace(0, np.pi, 3))

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [62]:
np.exp(np.linspace(0, 2, 3))

array([1.        , 2.71828183, 7.3890561 ])

#### Аргумент out

In [63]:
result = np.empty(9999)
np.sin(np.linspace(0, np.pi, 9999), out=result)

array([0.00000000e+00, 3.14222105e-04, 6.28444178e-04, ...,
       6.28444178e-04, 3.14222105e-04, 1.22464680e-16])

Jpython - Java

Cpython - C

#### reduce

Редуцирование массивов

In [12]:
np.add.reduce(np.array([1,2,3])) # Сумма всех элементов

6

In [65]:
np.multiply.reduce(np.array([1,2,3,4])) # Произведение всех элементов

24

#### accumulate 

Накопление 

In [66]:
np.add.accumulate(np.array([1,2,3,4]))

array([ 1,  3,  6, 10])

#### Векторное произведение (со всеми парами)- outer

Таблица умножения

In [4]:
first = np.arange(2, 10)

In [5]:
second = np.arange(2, 10)

In [14]:
first

array([2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
second

array([2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.multiply.outer(first, first)

array([[ 4,  6,  8, 10, 12, 14, 16, 18],
       [ 6,  9, 12, 15, 18, 21, 24, 27],
       [ 8, 12, 16, 20, 24, 28, 32, 36],
       [10, 15, 20, 25, 30, 35, 40, 45],
       [12, 18, 24, 30, 36, 42, 48, 54],
       [14, 21, 28, 35, 42, 49, 56, 63],
       [16, 24, 32, 40, 48, 56, 64, 72],
       [18, 27, 36, 45, 54, 63, 72, 81]])

---

## Агрегирование 

> * np.sum()
* np.min()
* np.max()
* np.mean() - среднее значение


In [22]:
np.mean(np.random.randint(1,10000,10))

4967.7

In [88]:
a = np.arange(100).reshape((10, 10))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [89]:
np.sum(a) # Сумма всех элементов

4950

Для того чтобы в многомерном массиве найти средние значения каждого столбца:

In [92]:
np.sum(a, axis=0)

array([450, 460, 470, 480, 490, 500, 510, 520, 530, 540])

Строки:

In [93]:
np.sum(a, axis=1)

array([ 45, 145, 245, 345, 445, 545, 645, 745, 845, 945])

#### Другие функции агрегирования
NaN-safe - позволяют некоторым элементам быть пустыми

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |
