![NumPy Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png)

# Основы Numpy *(Numerical Python)* 
# Часть 2

## [Документация](https://docs.scipy.org/doc/numpy/reference/)

In [2]:
import numpy as np

---

## Простейшие операции с массивами

>* атрибуты
* индексация
* срезы
* изменение формы
* слияние и разбиение

---

## Атрибуты массивов

In [3]:
a = np.random.randint(1,5,(3,4))
a

array([[3, 3, 2, 3],
       [3, 1, 1, 4],
       [1, 3, 4, 2]])

#### Размер- общее количество элементов 

In [3]:
a.size

12

#### Количество измерений(мерность)

In [4]:
a.ndim

2

#### Тип элементов

In [5]:
a.dtype

dtype('int64')

#### Форма массива 

In [6]:
a.shape

(3, 4)

#### Размер элемента в байтах

In [4]:
a.itemsize 

96

In [8]:
a

array([[2, 2, 4, 2],
       [3, 1, 4, 1],
       [4, 3, 2, 1]])

In [9]:
a

array([[2, 2, 4, 2],
       [3, 1, 4, 1],
       [4, 3, 2, 1]])

---

## Индексация

#### Доступ к конкретному элементу 

In [10]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
b[0]

array([1, 2, 3])

In [13]:
b[0,1]

2

In [14]:
b[-1]

array([7, 8, 9])

In [15]:
b[-1,-2]

8

#### Можно записать значение 

In [16]:
b[0,0] = 999

In [17]:
b

array([[999,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

 > ## **Важное замечание**:
Так как, в numpy все элементы массива одного типа, если записать дробное число в целочисленный массив- число обрежется.

In [18]:
b[1,1] = 1.23
b

array([[999,   2,   3],
       [  4,   1,   6],
       [  7,   8,   9]])

---

## Срезы 

> **[начало:конец:шаг]**

In [6]:
c = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34],[41,42,43,44],])
c

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

### Одномерные

In [20]:
c[1:]

array([[21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [21]:
c[:3]

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

### Многомерные 

In [22]:
c[::2]

array([[11, 12, 13, 14],
       [31, 32, 33, 34]])

In [23]:
c[1::2]

array([[21, 22, 23, 24],
       [41, 42, 43, 44]])

In [24]:
c[:,2:]

array([[13, 14],
       [23, 24],
       [33, 34],
       [43, 44]])

In [8]:
c[1:-1,1:-1]

array([[22, 23],
       [32, 33]])

In [9]:
c[::-1,::-1]

array([[44, 43, 42, 41],
       [34, 33, 32, 31],
       [24, 23, 22, 21],
       [14, 13, 12, 11]])

In [3]:
z = np.zeros((8,8))
z[1::2, ::2] = 1
z[::2, 1::2] = 1
z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [27]:
c[:, 2]

array([13, 23, 33, 43])

### Копирование массивов  

##### Пример
Берем срез из массива с:

In [28]:
d = c[1:-1,1:-1]
d

array([[22, 23],
       [32, 33]])

И изменяем его:

In [29]:
d[0,0] = 999

In [30]:
d

array([[999,  23],
       [ 32,  33]])

При этом неочевидным образом меняется и массив **c**

In [31]:
c

array([[ 11,  12,  13,  14],
       [ 21, 999,  23,  24],
       [ 31,  32,  33,  34],
       [ 41,  42,  43,  44]])

Поэтому мы должны использовать в этом случае, и просто, в случае копирования массивов метод **copy**

In [11]:
d = np.copy(c)

---

In [ ]:
a = [1,2,3]

In [12]:
b = a[:]

In [ ]:
b = a.copy()

---

## Изменение формы массивов

In [13]:
d

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [33]:
d.reshape(8,2)

array([[ 11,  12],
       [ 13,  14],
       [ 21, 999],
       [ 23,  24],
       [ 31,  32],
       [ 33,  34],
       [ 41,  42],
       [ 43,  44]])

#### Преобразование одномерного массива в столбец 

In [14]:
np.array([1,2,3,4])[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

---

## Слияние и разбиение

### Слияние 

In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [18]:
a + b

array([5, 7, 9])

In [36]:
c = np.concatenate([a,b])

In [22]:
l = [a,b,c,c]


In [23]:
c = np.concatenate(l)

In [24]:
c

array([1, 2, 3, 4, 5, 6, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1,
       2, 3, 4, 5, 6, 1, 2, 3])

*concatenate* работает только для массивов одинаковой формы

In [25]:
c = np.array([[1,2,3],
              [4,5,6]])
d = np.array([[7,8,9],
             [10,11,12]])

In [50]:
np.concatenate([c,d], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
np.concatenate([c,d], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Для объединения массивов разной формы используется:
>* hstack - горизонтально
* vstack - вертикально
* dstack - по третьей оси

In [28]:
e = np.array([1,2,3])
f = np.array([[4,5,6],
              [7,8,9]])

In [29]:
np.vstack([e,f])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
g = np.array([[1],
              [2]])

In [31]:
np.hstack([f, g])

array([[4, 5, 6, 1],
       [7, 8, 9, 2]])

In [32]:
np.hstack([g, f])

array([[1, 4, 5, 6],
       [2, 7, 8, 9]])

In [33]:
np.dstack([f,f])

array([[[4, 4],
        [5, 5],
        [6, 6]],

       [[7, 7],
        [8, 8],
        [9, 9]]])

---

### Разбиение массивов 

Для разбиения массивов используется:
>* split
* vsplit - горизонтально
* hsplit - вертикально
* dsplit - по третьей оси

Каждому этому методу передается список точек раздела

In [35]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.split(a, [1])

[array([0]), array([1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [75]:
np.split(a, [3, 5])

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9])]

In [37]:
b = np.arange(16).reshape((4,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [80]:
vs1, vs2 = np.vsplit(b, [2])

In [81]:
vs1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [82]:
vs2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
np.hsplit(b, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [86]:
np.hsplit(b, [3])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]