## [Документация](https://docs.scipy.org/doc/numpy/reference/)

![NumPy Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png)

# Основы Numpy *(Numerical Python)* 
# Часть 1

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.4'

***

### Создание массивов из списков 

In [5]:
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
np.array([range(i, i+5) for i in range(5)])

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

>#### Типы numpy:
* int
    * int32, int 64
* uint
* float
* bool
* complex

In [5]:
np.array([1, 2, 3], dtype="int64")

array([1, 2, 3])

***

### Создание массивов с нуля

#### Массив полностью из нулей (одномерный) 

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Массив полностью из нулей (заданной формы)

In [7]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### Массив единиц

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

#### Массив с одинаковыми значениями 

In [9]:
np.full((3,3), np.pi)

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

####  Массив из последовательности чисел- по аналогии с range

In [10]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

#### Массив из последовательности чисел, равномерно распределенных между 1м и 2м аргументом

In [11]:
np.linspace(0, 15, 10)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        , 11.66666667, 13.33333333, 15.        ])

#### Единичная матрица 

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Неинициализированные значения(произвольные значения из памяти) 

In [13]:
np.empty((3,3))

array([[ 1.66666667,  3.33333333,  5.        ],
       [ 6.66666667,  8.33333333, 10.        ],
       [11.66666667, 13.33333333, 15.        ]])

### Случайное задание элементов 

#### От 0 до 1 (в скобках задается форма)  

In [14]:
np.random.random((2,2))

array([[0.88867944, 0.4204965 ],
       [0.56414219, 0.03679428]])

#### Целые значения от 1 до 5 в массив формы 2x2

In [15]:
np.random.randint(1, 5, (2, 2))

array([[1, 4],
       [3, 2]])

#### Нормальное распределение с медианой 0 и стандартным отклонением 1

In [16]:
np.random.normal(0, 1, 3)

array([ 0.35187108, -1.06868088,  0.65604847])